import streamlit as st
import numpy as np
import plotly.graph_objects as go

st.set_page_config(page_title="Compactified Riemann Helix — Aligned Zeros", layout="wide")
st.title("Compactified Riemann Helix on Cylinder")
st.markdown("""
**Zeros fixed at identical angle** (generator $\\theta=0$) while prime logarithms determine the periodic torsion.
Sliders control the compactification scale $\\lambda$, the number of torsion modes $N$, and the number of displayed zeros.
The cylinder height $L=2\\log\\lambda$ is the compactification period; ends are identified in the model.
""")

# --------------------------- Sidebar controls ---------------------------
with st.sidebar:
    st.header("Parameters")
    lambda_val = st.slider("λ (scaling parameter)", 2.8, 18.0, 6.5, 0.1)
    N = st.slider("N (prime / Fourier modes)", 5, 28, 12, 1)
    num_z = st.slider("Number of zeros", 5, 24, 15, 1)
    main_rate = st.slider("Base winding rate", 12.0, 38.0, 23.0, 0.5)
    bump_scale = st.slider("Torsion bump amplitude", 1.0, 7.0, 3.8, 0.2)
    sigma = st.slider("Bump width σ", 0.06, 0.25, 0.12, 0.01)

L = 2 * np.log(lambda_val)

# --------------------------- Data preparation ---------------------------
gamma = np.array([
    14.134725, 21.022040, 25.010858, 30.424876, 32.935062, 37.586178,
    40.918719, 43.327073, 48.005151, 49.773832, 52.970321, 56.446248,
    59.347044, 60.831779, 65.112544, 67.079811, 69.546402, 72.067158,
    75.704691, 77.144840, 79.337375, 82.910136, 84.735493, 87.425275
])

primes = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97]
log_ps = [np.log(p) for p in primes if np.log(p) < L][:N]

x = np.linspace(0, L, 1400)
dx = x[1] - x[0]

# Torsion rate = main + prime bumps (periodic via log p mod L)
dtheta = np.full_like(x, main_rate)
for lp in log_ps:
    dtheta += bump_scale * np.exp(-(x - lp)**2 / (2 * sigma**2))

theta = np.cumsum(dtheta) * dx
theta = theta - theta[0]          # start at angle 0

# Cylinder surface
theta_c = np.linspace(0, 2*np.pi, 64)
z_c = np.linspace(0, L, 48)
T, Z = np.meshgrid(theta_c, z_c)
X_cyl = np.cos(T)
Y_cyl = np.sin(T)
Z_cyl = Z

# Helix curve on cylinder
X_h = np.cos(theta)
Y_h = np.sin(theta)
Z_h = x

# Zeros — forced exactly at θ = 0 (same generator for every rotation)
x_z = np.log(gamma)
valid = x_z < L
x_z = x_z[valid][:num_z]
X_z = np.ones_like(x_z) * 1.06      # slightly outside cylinder for visibility
Y_z = np.zeros_like(x_z)            # exactly θ = 0
Z_z = x_z

# --------------------------- Plotly figure ---------------------------
fig = go.Figure()

# Cylinder surface (semi-transparent)
fig.add_trace(go.Surface(
    x=X_cyl, y=Y_cyl, z=Z_cyl,
    colorscale=[[0, '#e8e8e8'], [1, '#d0d0d0']],
    opacity=0.22,
    showscale=False,
    name="Cylinder"
))

# Helix curve
fig.add_trace(go.Scatter3d(
    x=X_h, y=Y_h, z=Z_h,
    mode='lines',
    line=dict(color='#1a3c8e', width=5),
    name="Helix (prime-modulated torsion)"
))

# Zeros — all at identical angle
fig.add_trace(go.Scatter3d(
    x=X_z, y=Y_z, z=Z_z,
    mode='markers+text',
    marker=dict(size=9, color='#c62828', symbol='circle'),
    text=[f"γ={g:.2f}" for g in gamma[valid][:num_z]],
    textposition="top center",
    textfont=dict(size=9, color='#4a148c'),
    name="Zeros (fixed angle θ=0)"
))

fig.update_layout(
    title=dict(
        text=f"Compactified Cylinder (L = {L:.3f}, λ = {lambda_val:.2f}) — Zeros aligned on generator θ = 0",
        font=dict(size=16, color='#1a3c5e')
    ),
    scene=dict(
        xaxis=dict(title="X", range=[-1.4, 1.4], showbackground=False),
        yaxis=dict(title="Y", range=[-1.4, 1.4], showbackground=False),
        zaxis=dict(title="x = log t (periodic 0→L)", range=[-0.2, L+0.3]),
        aspectmode='manual',
        aspectratio=dict(x=1, y=1, z=1.6),
        camera=dict(eye=dict(x=1.35, y=1.35, z=0.75))
    ),
    legend=dict(orientation="h", yanchor="bottom", y=0.02, xanchor="center", x=0.5),
    margin=dict(l=0, r=0, t=50, b=10),
    height=680
)

st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": True})

# --------------------------- Explanatory caption ---------------------------
st.caption(
    "All red markers lie on the single generator **θ = 0**. "
    "The continuous blue curve carries the full torsion generated by the folded prime logarithms. "
    "The finite height $L$ together with periodic torsion realises the compactification; "
    "the cylinder ends are identified in the model (CCM spectral triple)."
)